### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by nadongjin** [Android-for-Python/Camera4Kivy#1]
hello
There's a code I'm curious about.
Where is the on_size called?

=================================================================
lass HomeScreen0(SwipeScreen):
    
    def __init__(self, **args):
        super().__init__(**args)
        self.label = Label()
        self.add_widget(self.label)

    **def on_size(self, *args):**
        if self.width > self.height:
            COLS = 80
        else:
            COLS = 40
.................................................................
==================================================================

**Comment by Android-for-Python** [comment]
https://kivy.org/doc/stable/guide/events.html

Please address usage questions to the user groups
