### ISSUE TITLE
How to obtain position of saved image ?

### ISSUE THREAD

**Issue by USER4247** [Android-for-Python/Camera4Kivy#10]
I am implementing a scanner into kivy app using this module .  I did not quiet understood how can I get path of  Image .
Here is the code
`# camera remake
import fractions
from kivymd.app import MDApp 
from kivy.core.window import Window
from kivy.uix.screenmanager import ScreenManager
from kivy.utils import platform
#from android_permissions import AndroidPermissions
from camera4kivy import Preview
from fractions import Fraction
from kivy.lang import Builder
from toast import Toast
import Scanner
from kivy.properties import BooleanProperty, DictProperty, ListProperty, NumericProperty, ObjectProperty, OptionProperty, StringProperty
kv = """
MDBoxLayout:
    orientation: "vertical"
    Preview:
        id : preview
        aspect_ratio: app.ratio
    MDRoundFlatIconButton:
        text: "call cam"
        on_press: app.call_camera()
    MDRoundFlatIconButton:
        text: "uncall cam"
        on_press: app.disconnect()
    MDRoundFlatIconButton:
        text: "change cam"
        on_press: app.change_camera('toggle')
    MDRoundFlatIconButton:
        text: "image"
        on_press: app.caputure_image()
    MDRoundFlatIconButton:
        text: "vid start"
        on_press: app.video_start()
    MDRoundFlatIconButton:
        text: "vis stop"
        on_press: app.video_stop()
    MDRoundFlatIconButton:
        text: "scan"
        on_press: app.scan()
"""
class Cam(MDApp):
    h = Window.height
    w = Window.width
    ratio = str(h)+":"+str(w)
    photo_preview = ObjectProperty(None)
    def build(self):
        return Builder.load_string(kv)
    def call_camera(self):
        self.root.ids.preview.connect_camera()
    def disconnect(self):
        self.root.ids.preview.disconnect_camera()
    def change_camera(self,facing):
        self.root.ids.preview.select_camera(facing)
    def caputure_image(self):
        if self.root.ids.preview.camera_connected == True:
            self.path = self.root.ids.preview.filepath_callback
            self.root.ids.preview.capture_photo()
            print(self.path)
    def video_start(self):
        if self.root.ids.preview.camera_connected == True:
            self.root.ids.preview.capture_video()
    def video_stop(self):
        if self.root.ids.preview.camera_connected == True:
            self.root.ids.preview.stop_capture_video()
    def scan(self):
        if self.root.ids.preview.camera_connected == True:
            img = self.root.ids.preview.capture_photo()
            self.root.ids.preview.filepath_callback = self.scan_img
    def scan_img(self):
        Toast().show()
        print(Toast().show())
        #Scanner.Scanner.scan(file = str(path))
if __name__ == "__main__":
    Cam().run()

`
Thank you

**Comment by Android-for-Python** [comment]
Always indent Python code otherwise it is meaningless.

See this example: 
https://github.com/Android-for-Python/c4k_photo_example/blob/main/applayout/photoscreen1.py#L26
https://github.com/Android-for-Python/c4k_photo_example/blob/main/applayout/photoscreen1.py#L31-L32

And read the docs:
https://github.com/Android-for-Python/Camera4Kivy#filepath_callback

I won't debug or rewrite your code for you.
