### ISSUE TITLE
Kudos and two suggestions

### ISSUE THREAD

**Issue by MrBillium** [Android-for-Python/Camera4Kivy#11]
Thanks for writing this!

I have been struggling for about a week looking for a Kivy QR code scanner that would start, stop and restart the camera without hanging **AND run on new Android device.**
Anything I found that would run on Windows would not compile for Android or would compile but not produce an image. Lots of Rabbit holes including the deepest - OpenCV.
The Internet is littered with questions about failed Android builds with ‘try this’ answers followed by a conflicting ‘ try that’ answer.

I was about to give up when I stumbled on your github page.

First thing I noticed was instructions about  Buildozer.spec file  - Hmmm, so they actually have built this on mobile – keep reading…
Tested platforms --  keep reading …
Permissions code!  - perhaps Buildozer.spec, permissions = CAMERA is not  enough – keep reading..
Driver code!  - Perhaps I need a driver – nobody else mentioned this! – give it a try.

And, 20 mins later your QR example just works on my new Samsung tablet - 1st try !

Great work!

Two suggestions:
	
1.
Since browsers land on Github readme, in many repos the top of the file is a mission statement and/or elevator pitch.  I think you are selling yourselves short with  just _“ Yet Another Camera for Kivy”_!

Suggestion
Replace “ Yet Another Camera for Kivy” with reasons your library is better (it is!!) so more people will try it.

Something like:
Camera provider for Kivy with code & instructions to easily compile and run on many IOS and Android devices.
Features:

- Four examples  , **TESTED on mobile platforms** (see table) .Each includes Buildozer.spec file to make compiling easy.
- Image processing performed on another non-gui thead (to reduce stuttering?)
- Camera can be turned off and restarted in code.
- Run-time HW permissions requested and set from code.

2. 
The examples are found in the readme above the API documentation and will likely be viewed first (as expected).
But, it is hard for a newby to understand **why** they work (without first reading the API)  because you are using implicit callbacks.

Suggestion
Add inline comments to examples to show how/where callbacks are being called to make it clear.

Thanks again for building this.

**Comment by Android-for-Python** [comment]
Thanks.

The subtitle is a play on Yacc https://en.wikipedia.org/wiki/Yacc  (which most definitely was not another...). Prototypes of this package where named Yack, I think I had a marketing (!) concern about references changing the vowel - so I changed the name. So you are right, the subtitle is legacy documentation.

Point taken, perhaps a **Features** list at the top.
