### ISSUE TITLE
Pyinstaller and camera4kivy

### ISSUE THREAD

**Issue by ejbt11** [Android-for-Python/Camera4Kivy#13]
Hi,

I don't know if posting here is the right way to raise this issue, if not kindly close this concern. I am a beginner kivy developer. I love how fast your camera library is on windows.

It is working properly while running in VScode debug mode, but when compiled with pyinstaller as exe, the Preview Widget cannot find any camera provider. It only shows a gray screen with ERROR message - ERROR: No camera provider found.

my pyinstaller spec is the following:
`# -*- mode: python ; coding: utf-8 -*-

from kivy_deps import sdl2, glew, gstreamer
from kivy.tools.packaging import pyinstaller_hooks as hooks

block_cipher = None
kivy_deps_all = hooks.get_deps_minimal(
    window=['sdl2'],
    text=['sdl2'],
    clipboard=['sdl2'],
    image=['sdl2'],
    camera=['opencv'],
    audio=['sdl2'],
    video=None,
    spelling=None)

kivy_factory_modules = hooks.get_factory_modules()
hiddenimports = kivy_deps_all['hiddenimports'] + kivy_factory_modules
hiddenimports += [
    'camera4kivy',
]

a = Analysis(
    ['warehouse_app\\main.py'],
    pathex=[],
    binaries=[],
    datas=[('warehouse_app/assets/*', '.')],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes= kivy_deps_all['excludes'] + ['Tkinter', '_tkinter', 'twisted', 'docutils', 'pygments'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    Tree("D:\\kivy-warehouse\\warehouse_app\\"),
    a.zipfiles,
    a.datas,
    *[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins)],
    name='warehouse',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='warehouse.ico',
)`

**Comment by RobertFlatt** [comment]
I know nothing about configuring pyinstaller, and yes it is off topic here.

However, eyeballing the script above, perhaps the value of `camera=` should be https://github.com/Android-for-Python/camera4kivy#opencv

**Comment by ejbt11** [comment]
Hi Robert,

Thank you for the response, will raise this on kivy or pyinstaller thread. Do you have any recommended compiler for windows exe regarding camera4kivy? Thanks.

**Comment by ejbt11** [comment]
P.S. I have reverted back to the slow kivy camera widget for now. The pyinstaller config above works properly with kivy camera. I'll close the ticket after your response. Thank you so much!
