### ISSUE TITLE
Is it possible to render the preview into a dialogue?

### ISSUE THREAD

**Issue by xavierfiechter** [Android-for-Python/Camera4Kivy#14]
Hi all,

Is there a way to render the preview into a dialogue (with `type="custom", ..`), into the red area?

If yes, how? 

Wasn't able to get it running. 

Trial'ed and error'ed, also got this error: 

```
File "~/env/lib/python3.10/site-packages/camera4kivy/preview_kivycamera.py", line 278, in on_tex
     tex = self._camera.texture.get_region(*self.tex_crop)
 AttributeError: 'NoneType' object has no attribute 'get_region'
```
In my case, `self._camera.texture` is None. 

 
<img width="405" alt="Screenshot 2022-12-18 at 01 52 46" src="https://user-images.githubusercontent.com/31884704/208271957-67ab45d1-ed52-4689-a361-78ed19905e67.png">

**Comment by Android-for-Python** [comment]
> `self._camera.texture is None`.

It looks like the camera is not connected to the Preview widget; the details of the nature of the issue, or the reason for cryptic error message are unclear.

The question is perhaps, where we see the (Label?) text, why is there no layout space containing an empty (non-functional) Preview and the surrounding letterbox? Because that would be a prerequisite.

> dialogue (with type="custom", ..), 

Perhaps this refers to a KivyMD MDDialog, I know nothing about this, sorry, I'd probably test with a Kivy ModalView or Popup first. Connecting on_open(), disconnecting on_pre_dismiss(). But personally I have never tried this,

**Comment by xavierfiechter** [comment]
Thanks for your replay. 

Works in a Modal and a Popup, but only if the preview is initialized directly. As soon as I try to cascade the elements, I get the ` AttributeError: 'NoneType' object has no attribute 'get_region'` error.

**Comment by Android-for-Python** [comment]
Please expand on what you mean by 'only if the preview is initialized directly' and 'cascade the elements'. Thanks.

**Comment by xavierfiechter** [comment]
This works:

```
def show_preview_modal(self):
        self._qr_preview_modal = ModalView(size_hint=(None, None), size=(480, 640))
        self._qr_preview_modal.add_widget(self._qrreader)
        self._qr_preview_modal.on_pre_dismiss = partial(self.qrreader_release)
        self._qr_preview_modal.open()
        self._qrreader.connect_camera(analyze_pixels_resolution = 640, enable_analyze_pixels = True)
```

This does not work:

```
def show_preview_modal(self):
        self._qr_preview_modal = ModalView(size_hint=(None, None), size=(480, 640))
        box = BoxLayout( .. )
        box.add_widget( Label( .. ) )
        box.add_widget(self._qrreader)
        box.add_widget( FlatButton( .. ) )
        self._qr_preview_modal.add_widget(box)
        self._qr_preview_modal.on_pre_dismiss = partial(self.qrreader_release)
        self._qr_preview_modal.open()
        self._qrreader.connect_camera(analyze_pixels_resolution = 640, enable_analyze_pixels = True)
```

This doesn't work either: 


```
- Box 
 -- Label
 -- Preview() / _qrreader 
 -- Button 
```
 
 nor 

```
- Preview() / _qrreader 
- Box 
 -- Label
 -- Button 
```

**Comment by Android-for-Python** [comment]
I wonder it is race condition related to the time to build the layout? Perhaps modal.open() is not blocking.

Try setting `self._qr_preview_modal.on_open = self.method_calling_connect_camera()` and removing the existing `connect_camera`.

**Comment by xavierfiechter** [comment]
Thanks for your suggestion and hints. 

Works great with the modal.
