### ISSUE TITLE
Turn on Flash during Preview mode Camera4Kivy

### ISSUE THREAD

**Issue by farhanalfin** [Android-for-Python/Camera4Kivy#15]
I used Camera4Kiby to develop an applicatipon using phone camera to process the catched image, I need the flash during using opencv for image processing.
is there anyway to turn flashlight during camera preview.

**Comment by Android-for-Python** [comment]
Not implemented, but assuming the question is on Android this user hacked it "Although it is not an elegant way" (though it doesn't look bad to me)

https://github.com/Android-for-Python/c4k_qr_example/issues/1#issuecomment-1254498788

Two of you seems enough interest to add this feature to my todo list....

Close?

**Comment by farhanalfin** [comment]
Thanks a lot, I will give it a try
