### ISSUE TITLE
feature request: callback for image capture without file write

### ISSUE THREAD

**Issue by lane-westlund** [Android-for-Python/Camera4Kivy#17]
I am currently developing an app which where the goal is to periodically take a photo and process it (but only save a final photo after some time).

Currently I use [enable_analyze_pixels](https://github.com/Android-for-Python/Camera4Kivy#enable-analyze-pixels) for this, however the resolution of the image I obtain from this is not as high as the image which is output via the photo capture which writes to a file.  I have tried setting it, but on my android (pixel 6 Pro, android 13) it seems to be limited to 2236x1258 instead of the desired 4080x4072 (or 16:19 equivalent)

I would like to avoid excessively writing and deleting files, so it would be nice to have a callback which simply gets the photo's bytes without them being written directly to a file. I believe android OS supports such a callback: [OnImageCapturedCallback](https://developer.android.com/reference/androidx/camera/core/ImageCapture.OnImageCapturedCallback) used by [ImageCapture.takePicture()](https://developer.android.com/reference/androidx/camera/core/ImageCapture#takePicture(java.util.concurrent.Executor,androidx.camera.core.ImageCapture.OnImageCapturedCallback))

**Comment by Android-for-Python** [comment]
Yes, the analyze api is not going to be optimal for this use case. Top of my head I don't know where the size constraint you see is coming from, but I expect it is cameraX - it does stuff like that you may not get desired size, I don't know if that will be different with ImageCapturedCallback  (currently uses ImageSavedCallback).

Thus some c4k option would command return memory ref, Do you envision the c4k callback returning a memory reference in place of a string? Android would return an ImageProxy (presumably bgr or yuv420, if in buffers this may only be visible from Java - have to test), should the returned reference be something Python friendly or is ImageProxy better?

Food for thought at the moment, I got other things....

**Comment by Android-for-Python** [comment]
> that will I think be the best resolution CameraX will provide.
Forget that, that is only from the analyze use case, photo use case may be different.

**Comment by Android-for-Python** [comment]
Note to self: Also the image will have to be rotated depending on the device hardware, or also return rotation angle.

**Comment by Android-for-Python** [comment]
What is the issue with saving a jpeg to private storage, then reading and deleting from the c4k image saved callback?

**Comment by lane-westlund** [comment]
> What is the issue with saving a jpeg to private storage, then reading and deleting from the c4k image saved callback?

I'm hesitant to use flash in this way as it has a finite lifetime, so I'd prefer to avoid unnecessary read/write operations like this

**Comment by Android-for-Python** [comment]
Well to me the idea is interesting, and probably *could* be implemented in a platform independent way. 
Its not clear to be that it *should* be implemented.

The positives seem to be elegance, and storage lifetime.
The negatives seem to be (mostly) no new behavior, no other requests, and prioritizing against other tasks.

The memory lifetime argument is an interesting one, but not something I feel the need to be responsible for. 

I'll keep the idea around, but for now no action.

If it is important to you I suggest you fork c4k and camerax_provider.
