### ISSUE TITLE
Far focus on load

### ISSUE THREAD

**Issue by odudex** [Android-for-Python/Camera4Kivy#18]
I built an application starting from the QR code scanner example. It works well, but there's something that bothers me. Maybe I'm doing something wrong, but when I run the camera its focus start at infinite, then it takes about 3 seconds to auto-focus adjust so it's possible to scan a QR code. Is there some way to start the camera with focus set to a closer distance?

**Comment by Android-for-Python** [comment]
Tap for focus (assuming the hardware supports it) is the only focus control. 

You can access the api for that https://github.com/Android-for-Python/Camera4Kivy#focus *after* the camera is connected. 

Or you could try increasing the `analyze_pixels_resolution`
