### ISSUE TITLE
Version 0.2.0 give an error

### ISSUE THREAD

**Issue by farhanalfin** [Android-for-Python/Camera4Kivy#19]
File "C:\Program Files\Python311\Lib\site-packages\camera4kivy\preview_kivycamera.py", line 69, in on_size
     self.on_tex(None)
   File "C:\Program Files\Python311\Lib\site-packages\camera4kivy\preview_kivycamera.py", line 345, in on_tex
     tex = self._camera.texture.get_region(*self.tex_crop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 AttributeError: 'NoneType' object has no attribute 'get_region'

**Comment by Android-for-Python** [comment]
Can you please provide some context. 
- a small example
- or a description of what events give rise to this issue.

Thanks

**Comment by farhanalfin** [comment]
I tested it with my project and to be sure I tested now with c4k opencv
example and gave the same error

Thanks

**Comment by farhanalfin** [comment]
"C:\Program Files\Python311\python.exe"
C:\Users\newge\PycharmProjects\Kivy\Kivy_Camera\c4k_opencv_example-main\main.py

[INFO   ] [Logger      ] Record log in
C:\Users\newge\.kivy\logs\kivy_23-02-17_7.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.3
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.5.1
[INFO   ] [Kivy        ] v2.2.0.dev0
[INFO   ] [Kivy        ] Installed at
"C:\Users\newge\AppData\Roaming\Python\Python311\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022,
19:58:39) [MSC v.1934 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "C:\Program
Files\Python311\python.exe"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 190 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil
(img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 511.69'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce 930MX/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not
docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Camera      ] Provider: opencv
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File
"C:\Users\newge\PycharmProjects\Kivy\Kivy_Camera\c4k_opencv_example-main\main.py",
line 54, in <module>
     MyApp().run()
   File
"C:\Users\newge\AppData\Roaming\Python\Python311\site-packages\kivy\app.py",
line 956, in run
     runTouchApp()
   File
"C:\Users\newge\AppData\Roaming\Python\Python311\site-packages\kivy\base.py",
line 574, in runTouchApp
     EventLoop.mainloop()
   File
"C:\Users\newge\AppData\Roaming\Python\Python311\site-packages\kivy\base.py",
line 339, in mainloop
     self.idle()
   File
"C:\Users\newge\AppData\Roaming\Python\Python311\site-packages\kivy\base.py",
line 391, in idle
     Clock.tick_draw()
   File
"C:\Users\newge\AppData\Roaming\Python\Python311\site-packages\kivy\clock.py",
line 783, in tick_draw
     self._process_events_before_frame()
   File "kivy\_clock.pyx", line 662, in
kivy._clock.CyClockBase._process_events_before_frame
   File "kivy\_clock.pyx", line 708, in
kivy._clock.CyClockBase._process_events_before_frame
   File "kivy\_clock.pyx", line 704, in
kivy._clock.CyClockBase._process_events_before_frame
   File "kivy\_clock.pyx", line 218, in kivy._clock.ClockEvent.tick
   File
"C:\Users\newge\AppData\Roaming\Python\Python311\site-packages\kivy\uix\anchorlayout.py",
line 122, in do_layout
     c.size = cw, ch
     ^^^^^^
   File "kivy\properties.pyx", line 520, in kivy.properties.Property.__set__
   File "kivy\properties.pyx", line 1478, in
kivy.properties.ReferenceListProperty.set
   File "kivy\properties.pyx", line 606, in
kivy.properties.Property._dispatch
   File "kivy\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
   File "kivy\_event.pyx", line 1213, in
kivy._event.EventObservers._dispatch
   File "C:\Program
Files\Python311\Lib\site-packages\camera4kivy\preview_kivycamera.py", line
69, in on_size
     self.on_tex(None)
   File "C:\Program
Files\Python311\Lib\site-packages\camera4kivy\preview_kivycamera.py", line
345, in on_tex
     tex = self._camera.texture.get_region(*self.tex_crop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 AttributeError: 'NoneType' object has no attribute 'get_region'

**Comment by Android-for-Python** [comment]
Got it. Thank you.

Fixed, version 0.2.1 published.
