### ISSUE TITLE
question

### ISSUE THREAD

**Issue by nadongjin** [Android-for-Python/Camera4Kivy#2]
I'm a beginner at kivy.
this is i'm really necessary function.
I want to how load the captured image into opencv after Capture an image with a camera4kivy
What should I do with camera4kivy?
Please help me.

**Comment by Android-for-Python** [comment]
Read the documentation <https://github.com/Android-for-Python/camera4kivy#image-analysis> and read and try the examples <https://github.com/Android-for-Python/camera4kivy#examples>

If you want beginner help, try the user groups:
https://groups.google.com/g/kivy-users
https://discord.gg/55AzDeMD
