### ISSUE TITLE
Problem with new version of CameraX 

### ISSUE THREAD

**Issue by SergioPovoli** [Android-for-Python/Camera4Kivy#21]
I upgrade the CameraX provider, and now I have a problem with `connect_camera().` 
In particular, the camera of my OnePlus 6 is not connecting on_enter, while if I press a button to call `select_camera(),` it works, and the camera starts to connect. 

Any possible reason for the problem?

**Comment by Android-for-Python** [comment]
Thank you.

Would you try a simple test to see if this fixes the issue?

C4k uses the latest release camerax api version, this is specified in `camerax_provider/gradle_options.py` like this https://github.com/Android-for-Python/camerax_provider/blob/0.0.3/gradle_options.py#L27-L31

Please try an older version of camerax. Edit `camerax_provider/gradle_options.py` to this https://github.com/Android-for-Python/camerax_provider/blob/0.0.2/gradle_options.py#L27-L31   

(this is not exactly the same as going back a version) 

`buildozer appclean`....

**Comment by Android-for-Python** [comment]
Quick sanity check. Is this on the first screen?  
If so Kivy calls on_enter before on_start, which might cause what you see.

**Comment by Android-for-Python** [comment]
Looking for some feedback.
Is the issue addressed?
Was it a first screen issue?
Was it a gradle_dependencies issue?
Thanks.

**Comment by SergioPovoli** [comment]
Hi, 
I apparently resolve the problem using: `connect_camera(enable_video = False, ...other options..)`

1) No, it isn't a first-screen issue
2) Whit the older version of cameraX, there is no issue.

**Comment by Android-for-Python** [comment]
Thanks for the feedback.

I will update the documentation to match.
