### ISSUE TITLE
Feature request. Wide angle camera lens.

### ISSUE THREAD

**Issue by jamanz** [Android-for-Python/Camera4Kivy#22]
Dear developers please add option to chose phone wide angle camera lens if it available.

**Comment by Android-for-Python** [comment]
Will do. Very approximately, it will be a couple of months.

**Comment by Android-for-Python** [comment]
Turns out this change must be implemented in Kivy, here 
https://github.com/kivy/kivy/blob/master/kivy/core/camera/camera_avfoundation_implem.m 

I do not plan to do this.
