### ISSUE TITLE
C4K TFlite example runs much slower than expected

### ISSUE THREAD

**Issue by alonelycharmander** [Android-for-Python/Camera4Kivy#23]
We are trying to reproduce the Camera4Kivy speed results listed in this example repo: https://github.com/Android-for-Python/c4k_tflite_example
We were able to deploy that repo to our Android Pixel 6 phone without any issues, but the FPS is less than half of the claimed 27 FPS.  We were wondering why this could be?  (We were unable to post an issue to that repo, so we figured here would be the most appropriate place.)

The only changes we made to the c4k_tflite_example was to classifyobject.py in order to show an easier-to-read and more stable FPS number (see attached patch file).

**Environment:**
	-Pixel 6: Android version 13
	-tflite-runtime: 2.12
	-Python 3.8
	-Source Version: c4k_tflite_example
	
**Describe the bug:**

c4k_tflite_example fails to reach 27 annotations per sec. It fluctuates around 10.4 - 11.0 FPS.

![c4kTfliteexampleFPS](https://github.com/Android-for-Python/Android-for-Python-Users/assets/70731793/25009920-f8c6-44bc-90c8-5f7a0d3c2f4f)

**To Reproduce:** 
	
	1. Clone the master branch of https://github.com/Android-for-Python/c4k_tflite_example
	2. Apply patches in classifyobjects.patch
	3. Deploy to Pixel 6 phone

[classifyobject.patch](https://github.com/Android-for-Python/Android-for-Python-Users/files/12045138/classifyobject.patch)

**Comment by RobertFlatt** [comment]
Then don't change the example!

**Comment by alonelycharmander** [comment]
Thank you for the reply.  I'm not sure that was the issue though. Here's a screen shot of the example with same environment as stated before a clean copy of https://github.com/Android-for-Python/c4k_tflite_example, no changes.  
Still running at below half the expected FPS - and it fluctuates more, between  9.2-13.3 FPS on each object.

![FPStestPixel6noMod](https://github.com/Android-for-Python/Camera4Kivy/assets/70731793/9a919464-9f18-4908-9fc3-51b93dd2ae3b)
