### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Sp00nyMan** [Android-for-Python/Camera4Kivy#3]
Hello. Is there a way to apply a mask to the image we receive from the camera? 
I have a 0-1 matrix mask and need to fill all pixels of the input image corresponing with 0s only.
How can I do it considering the fact that the performance must not be affected severely.

**Comment by Android-for-Python** [comment]
If the question is how to use the image analysis api, see the docs

https://github.com/Android-for-Python/camera4kivy#image-analysis
and this example manipulates the preview image
https://github.com/Android-for-Python/c4k_opencv_example/blob/main/edgedetect.py

If the question is how to manipulate RGBA bitmaps in Python.
Pillow and opencv are options that I know of.
Easy to try and measure the execution times of whatever is used.

**Comment by Sp00nyMan** [comment]
Thank you very much for the answer. The second example does exactly what I needed.

**Comment by Sp00nyMan** [comment]
Hello again. I have noticed that the rate at which canvas_instructions_callback is called is quite low (about 8 times ps) on my laptop even with no extra instructions at all (just preview). Is there a way to increase it somehow? And if not is there any alternative way to use the kivy.uix.Camera widget but with image scaling and adaptation to various screen sizes?

**Comment by Android-for-Python** [comment]
The canvas update is triggered by Kivy's event loop, nothing special there. 

I wrote his because I am not a fan of Kivy Camera.

**Comment by Sp00nyMan** [comment]
Thank you very much for your efforts)
I have tested the same code on my android device and it gave me full 30fps. Apparently, the problem of low performance on my laptop might be caused by your PreviewKivyCamera class or opencv itself

**Comment by Android-for-Python** [comment]
That is good news. For my future reference, can you please tell me what camera provider was used on the laptop? 

Testing here showed one issue, but it is not yours  https://github.com/Android-for-Python/Camera4Kivy#behavior-raspberry-pi-video-frame-rate-is-lower-than-other-platforms

**Comment by Sp00nyMan** [comment]
I use Windows 10 and opencv as the provider

**Comment by Android-for-Python** [comment]
Thanks.
