### ISSUE TITLE
analyze_pixels_callback pixels parameter stay after disconnect_camera and connect again

### ISSUE THREAD

**Issue by farhanalfin** [Android-for-Python/Camera4Kivy#4]
to perform a Colour - Checker Detection https://github.com/colour-science/colour-checker-detection I used Camera4Kivy with enabled analyze_pixels_callback., and when finding the chart make the program swapping the screen to correction screen. When make the program came back  to the detection screen the analyze_pixels_callback uses the old image pixels. How I can enforce the analyze_pixels_callback to use a new pixels.

**Comment by Android-for-Python** [comment]
The pixels are unchanged during an analyze_pixels_callback, and change with each analyze_pixels_callback. 

This callback occurs at the maximum available rate, this depends on the camera, the device GPU, and the latency of functionality implemented in analyze_pixels_callback. 

See any of the examples for thread safe usage of the result.

**Comment by farhanalfin** [comment]
Ok. may be I did not explain my issue. I build an application with a screenmanager and in every screen a have a class of vamera4kivy preview with enable_analyze_pixels=True. Screen1 to have the pixels of preview, 

def analyze_pixels_callback(self, pixels, image_size, image_pos, scale, mirror):
        self.chart_image_pixels = pixels
        self.chart_image_size = image_size

to detect a color checker at self.chart_image_pixels in the main class.
Screen2 to show a rectangular with specified measurements over the image. 
The problem is after switching several times between screens the preview is frizzing. the application is running steady if 
 disabled  enable_analyze_pixels=False.

another question , is  there any way to have the pixels or texture of preview.

**Comment by Android-for-Python** [comment]
> The problem is after switching several times between screens the preview is frizzing

No way to know, but it sounds like memory corruption. Perhaps this is a camera provider issue, perhaps naturally or by abuse. Perhaps something about (you say) main class, not clear what is happening, but check the implementation is thread safe. 

>another question , is there any way to have the pixels or texture of preview.

If you want to get the Preview pixels, the analysis code uses a copy of the Preview pixels. If you want to set the Preview pixels see the opencv example. Else dig into the source code for the structure you want.
