### ISSUE TITLE
capture video

### ISSUE THREAD

**Issue by mujtabaoria1997** [Android-for-Python/Camera4Kivy#5]
Hi, i was trying to capture video but i think it isn't working. even when using location, subdir and filename still nothing happened. maybe i'm doing wrong. please help me.

**Comment by Android-for-Python** [comment]
As I understand it, the issue is using the c4k_photo_example with no changes, it is possible to capture a photo but not a video in the DCIM directory. Is this correct?

**Comment by mujtabaoria1997** [comment]
Yeah, capture photo is wroking

**Comment by Android-for-Python** [comment]
> using the c4k_photo_example with no changes,
1) You didn't answer this.

2) Please explain in detail what you mean by "not working", include specific symptoms. 

3) Check that your phone is tested with the camerax api 
https://developer.android.com/training/camerax/devices

**Comment by mujtabaoria1997** [comment]
Hi again, capture photo woks perfect but capture video ends with jvm failed

**Comment by Android-for-Python** [comment]
There is no possibility of providing help if you don't answer **all** the questions in detail.
You must answer  1) and 3) 
For 2) If you have an error message post the full log as a .txt
