### ISSUE TITLE
Camera resolution

### ISSUE THREAD

**Issue by Lunatik00** [Android-for-Python/Camera4Kivy#6]
It says that the default resolution is the max of the sensor, but my phone has 48MP (8000X6000) resolution and the picture in the example is taken at 2448X3264 or 3264x2448 depending on the orientation, I don't see the resolution to be ever set in the example, so I suppose this is either an error on the package or an error in the example.

Either way, it would be good if there was an example in how to set resolutions in the app itself, like the default camera app does (select from the list of resolutions).

**Comment by Android-for-Python** [comment]
Don't confuse the physical resolution of the sensor with the available resolution and aspect ratio of the camera provider. https://github.com/Android-for-Python/Camera4Kivy#sensor-resolution  

As to setting resolution, an example is not intended to be an exhaustive demonstration of features. If you are interested in features RTFM, in this case https://github.com/Android-for-Python/Camera4Kivy#sensor_resolution 

Providing a list of available resolution for a given device is not documented or implemented. In general this is not available across camera providers. I understand you would like it as a feature, but it is unlikely to happen in the foreseeable future, as the availability constraint means current design is the 'closest' provided by the camera provider, which will be provider specific.
