### ISSUE TITLE
Video capture

### ISSUE THREAD

**Issue by seonake** [Android-for-Python/Camera4Kivy#8]
Hi, i am not able to get a file with video capture.
This is the line of code that it is not working properly:

#for Android: self.cam.capture_video(location = 'shared', subdir='myapp', name='vid')
#Next line, W10 desktop:
self.cam.capture_video(location=".",subdir="vid",name="test")

Please, could you help?
Many thanks

**Comment by Android-for-Python** [comment]
Video capture is Android only
https://github.com/Android-for-Python/Camera4Kivy#capture

See also 
https://github.com/Android-for-Python/c4k_photo_example

**Comment by seonake** [comment]
Thanks. So, i can not test it on a pc...
I was confused: " On a desktop <location> is the current directory . [...]"

**Comment by Android-for-Python** [comment]
Yes, for photo and screenshot.

I will update the docs to try to be clearer.
