### ISSUE TITLE
camera4kivy generating error when performing the deploy

### ISSUE THREAD

**Issue by Osmar-Souza** [Android-for-Python/Camera4Kivy#9]
when passing p4.hook = camerax_provider/gradle_options.py in buildozer it is generating conflict, I am not able to deploy, can you help me? 
follow the buildozer log below:

[DEBUG]:   	Unzipping /home/osmar-henrique/.gradle/wrapper/dists/gradle-7.4.1-all/8bevta3mh7872g50ecurigeld/gradle-7.4.1-all.zip to /home/osmar-henrique/.gradle/wrapper/dists/gradle-7.4.1-all/8bevta3mh7872g50ecurigeld
[DEBUG]:   	Set executable permissions for: /home/osmar-henrique/.gradle/wrapper/dists/gradle-7.4.1-all/8bevta3mh7872g50ecurigeld/gradle-7.4.1/bin/gradle
[DEBUG]:   	
[DEBUG]:   	Welcome to Gradle 7.4.1!
[DEBUG]:   	
[DEBUG]:   	Here are the highlights of this release:
[DEBUG]:   	 - Aggregated test and JaCoCo reports
[DEBUG]:   	 - Marking additional test source directories as tests in IntelliJ
[DEBUG]:   	 - Support for Adoptium JDKs in Java toolchains
[DEBUG]:   	
[DEBUG]:   	For more details see https://docs.gradle.org/7.4.1/release-notes.html
[DEBUG]:   	
[DEBUG]:   	Starting a Gradle Daemon (subsequent builds will be faster)

[DEBUG]:   ect  FAILURE: Build failed with an exception.
[DEBUG]:   	
[DEBUG]:   	* Where:
[DEBUG]:   	Build file '/home/osmar-henrique/src/.buildozer/android/platform/build-arm64-v8a/dists/myapp/build.gradle' line: 23
[DEBUG]:   	
[DEBUG]:   	* What went wrong:
[DEBUG]:   	A problem occurred evaluating root project 'myapp'.
[DEBUG]:   	> Failed to apply plugin 'com.android.internal.application'.
[DEBUG]:   	   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
[DEBUG]:   	     You can try some of the following options:
[DEBUG]:   	       - changing the IDE settings.
[DEBUG]:   	       - changing the JAVA_HOME environment variable.
[DEBUG]:   	       - changing `org.gradle.java.home` in `gradle.properties`.
[DEBUG]:   	
[DEBUG]:   	* Try:
[DEBUG]:   	> Run with --stacktrace option to get the stack trace.
[DEBUG]:   	> Run with --info or --debug option to get more log output.
[DEBUG]:   	> Run with --scan to get full insights.
[DEBUG]:   	
[DEBUG]:   	* Get more help at https://help.gradle.org
[DEBUG]:   	
[DEBUG]:   	Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[DEBUG]:   	
[DEBUG]:   	You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[DEBUG]:   	
[DEBUG]:   	See https://docs.gradle.org/7.4.1/userguide/command_line_interface.html#sec:command_line_warnings
[DEBUG]:   	
[DEBUG]:   	BUILD FAILED in 1m 44s
[DEBUG]:   	
[DEBUG]:   	
Exception in thread background thread for pid 45473:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sh-1.14.3-py3.8.egg/sh.py", line 1641, in wrap
    fn(*rgs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/sh-1.14.3-py3.8.egg/sh.py", line 2569, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python3.8/dist-packages/sh-1.14.3-py3.8.egg/sh.py", line 2269, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python3.8/dist-packages/sh-1.14.3-py3.8.egg/sh.py", line 869, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/osmar-henrique/src/.buildozer/android/platform/build-arm64-v8a/dists/myapp/gradlew assembleDebug

  STDOUT:
Downloading https://services.gradle.org/distributions/gradle-7.4.1-all.zip
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /home/osmar-henrique/.gradle/wrapper/dists/gradle-7.4.1-all/8bevta3mh7872g50ecurigeld/gradle-7.4.1-all.zip to /home/osmar-henrique/.gradle/wrapper/dists/gradle-7.4.1-all/8bevta3mh7872g50ecurigeld
Set executable permissions for: /home/osmar-henrique/.gradle/wrapper/dists/gradle-7.4.1-all/8bevta3mh7872g50ecurigeld/gradle-7.4.1/bin/gradle

Welcome to Gradle 7.4.1!

Here are the highlights of this release:
 - Aggregated test and JaCoCo reports
 - Marking additional test source directories as tests in IntelliJ
 - Support for Adoptium JDKs in Java toolchains

For more details see https://docs.gradle.org/7.4.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/home/osmar-henrique/src/.buildozer/android/platform/build-arm64-v8a/dists/myapp/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating root project 'myapp'.
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 44s

[INFO]:    STDOUT (last 20 lines of 51):
[DEBUG]:   	
* Try:	
> Run with --stacktrace option to get the stack trace.	
> Run with --info or --debug option to get more log output.	
> Run with --scan to get full insights.	
	
* Get more help at https://help.gradle.org	
	
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.	
	
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.	
	
See https://docs.gradle.org/7.4.1/userguide/command_line_interface.html#sec:command_line_warnings	
	
BUILD FAILED in 1m 44s	

[INFO]:    STDERR:
	
[INFO]:    ENV:
export SHELL='/bin/bash'
export SESSION_MANAGER='local/osmarhenrique-VirtualBox:@/tmp/.ICE-unix/1520,unix/osmarhenrique-VirtualBox:/tmp/.ICE-unix/1520'
export QT_ACCESSIBILITY='1'
export COLORTERM='truecolor'
export XDG_CONFIG_DIRS='/etc/xdg/xdg-ubuntu:/etc/xdg'
export XDG_MENU_PREFIX='gnome-'
export GNOME_DESKTOP_SESSION_ID='this-is-deprecated'
export LANGUAGE='pt_BR:pt:en'
export GNOME_SHELL_SESSION_MODE='ubuntu'
export SSH_AUTH_SOCK='/run/user/1000/keyring/ssh'
export XMODIFIERS='@im=ibus'
export DESKTOP_SESSION='ubuntu'
export SSH_AGENT_PID='1482'
export GTK_MODULES='gail:atk-bridge'
export DBUS_STARTER_BUS_TYPE='session'
export PWD='/home/osmar-henrique/src'
export LOGNAME='osmar-henrique'
export XDG_SESSION_DESKTOP='ubuntu'
export XDG_SESSION_TYPE='x11'
export GPG_AGENT_INFO='/run/user/1000/gnupg/S.gpg-agent:0:1'
export XAUTHORITY='/run/user/1000/gdm/Xauthority'
export WINDOWPATH='2'
export HOME='/home/osmar-henrique'
export USERNAME='osmar-henrique'
export IM_CONFIG_PHASE='1'
export LANG='pt_BR.UTF-8'
export LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
export XDG_CURRENT_DESKTOP='ubuntu:GNOME'
export VTE_VERSION='6003'
export GNOME_TERMINAL_SCREEN='/org/gnome/Terminal/screen/791d4c78_df70_41ad_9d90_7d4df38afe35'
export INVOCATION_ID='f464999aea874fd691b6f7185ffaaebc'
export MANAGERPID='1270'
export LESSCLOSE='/usr/bin/lesspipe %s %s'
export XDG_SESSION_CLASS='user'
export TERM='xterm-256color'
export LESSOPEN='| /usr/bin/lesspipe %s'
export USER='osmar-henrique'
export GNOME_TERMINAL_SERVICE=':1.80'
export DISPLAY=':0'
export SHLVL='1'
export QT_IM_MODULE='ibus'
export DBUS_STARTER_ADDRESS='unix:path=/run/user/1000/bus,guid=75ac3faf1c22abaa392665476307c855'
export XDG_RUNTIME_DIR='/run/user/1000'
export JOURNAL_STREAM='8:33554'
export XDG_DATA_DIRS='/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop'
export PATH='/home/osmar-henrique/.buildozer/android/platform/apache-ant-1.9.4/bin:/home/osmar-henrique/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/osmar-henrique/.local/bin/'
export GDMSESSION='ubuntu'
export DBUS_SESSION_BUS_ADDRESS='unix:path=/run/user/1000/bus,guid=75ac3faf1c22abaa392665476307c855'
export _='/usr/local/bin/buildozer'
export PACKAGES_PATH='/home/osmar-henrique/.buildozer/android/packages'
export ANDROIDSDK='/home/osmar-henrique/.buildozer/android/platform/android-sdk'
export ANDROIDNDK='/home/osmar-henrique/.buildozer/android/platform/android-ndk-r23b'
export ANDROIDAPI='29'
export ANDROIDMINAPI='21'
export ANDROID_NDK_HOME='/home/osmar-henrique/.buildozer/android/platform/android-ndk-r23b'
export ANDROID_HOME='/home/osmar-henrique/.buildozer/android/platform/android-sdk'

[INFO]:    COMMAND:
cd /home/osmar-henrique/src/.buildozer/android/platform/build-arm64-v8a/dists/myapp && /home/osmar-henrique/src/.buildozer/android/platform/build-arm64-v8a/dists/myapp/gradlew assembleDebug

[WARNING]: ERROR: /home/osmar-henrique/src/.buildozer/android/platform/build-arm64-v8a/dists/myapp/gradlew failed!
WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
No setup.py/pyproject.toml used, copying full private data into .apk.
Applying Java source code patches...
Applying patch: src/patches/SDLActivity.java.patch

**Comment by Android-for-Python** [comment]
> ]: > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.

11, 13, 15(?), or 17 are all good
